### ISSUE TITLE
清空功能存在Bug

### ISSUE THREAD

**Issue by AlexLi320** [zhangyin-github/Geomystery#1]
在关卡中使用清空后进行重做，会导致直线工具绘制的直线无法被显示在屏幕上，但直线依然在逻辑上存在，可以通过绘制这些“看不到”的线来过关。

**Comment by imczz** [comment]
初始化控制器controller之后，控制器的显示屏outputCoordinates[0]，没有获得画布的大小（canvas的宽和高）
