### ISSUE TITLE
freestyle中绘图速度过快会导致程序崩溃

### ISSUE THREAD

**Issue by AlexLi320** [zhangyin-github/Geomystery#19]
过快向画布中添加新元素会导致多线程的执行中线程同步出现问题。

**Comment by imczz** [comment]
canvas每1/60s（fps=60）会遍历outpotList这个屏幕显示列表，曾经使用的是foreach(Geo geo in outputList)来遍历，当遍历的时候如果用户恰好添加了一个元素，这个元素会被添加到屏幕列表outputList中，此时就会抛出collection has been modified异常。现在简单的把foreach循环改成了for循环，增加元素的时候不会出现问题，但是自由模式可以自由删除几何元素，很可能会导致越界错误。这需要在循环中检测一个标志位，如果正在更改则放弃本次遍历。
